#!/usr/bin/env python
import os
from fire import Fire
from helpers.data_factory import DataFactory
from helpers.reddit_data_generator import RedditDataGenerator
from pathlib import Path
from moments.agent import AgentConfig
import yaml

DATA_MOUNT = "/home/user/app/dataset"


def generate_data(
    dataset_type: str,
    dataset_name: str,
    agent_kind: str,
    agent_id: str,
    agent_variant: str,
):
    data_generator = None
    match dataset_type:
        case "reddit":
            data_generator = RedditDataGenerator(
                dataset_name=dataset_name, dataset_path=DATA_MOUNT
            )

    with open(
        Path(os.path.dirname(os.path.realpath(__file__)))
        / "helpers"
        / "configs"
        / f"{agent_kind}-{agent_id}-{agent_variant}.yaml",
        "r",
        encoding="utf",
    ) as f:
        agent_config_dict = yaml.safe_load(f)

    agent_config = AgentConfig(
        kind=agent_config_dict["kind"],
        id=agent_config_dict["id"],
        variant=agent_config_dict["variant"],
        init=agent_config_dict["init"],
    )
    DataFactory.generate_data(data_generator, agent_config)


# The main routine just invokes the start function.
if __name__ == "__main__":
    Fire(generate_data)
